# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addSongWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addSongWindow(object):
    def setupUi(self, addSongWindow):
        addSongWindow.setObjectName("addSongWindow")
        addSongWindow.resize(738, 540)
        self.centralwidget = QtWidgets.QWidget(addSongWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.song_title = QtWidgets.QLineEdit(self.centralwidget)
        self.song_title.setGeometry(QtCore.QRect(10, 10, 310, 20))
        self.song_title.setObjectName("song_title")
        self.add_couplet_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_couplet_btn.setGeometry(QtCore.QRect(10, 320, 75, 23))
        self.add_couplet_btn.setObjectName("add_couplet_btn")
        self.add_chour_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_chour_btn.setGeometry(QtCore.QRect(90, 320, 75, 23))
        self.add_chour_btn.setObjectName("add_chour_btn")
        self.add_bridge_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_bridge_btn.setGeometry(QtCore.QRect(170, 320, 75, 23))
        self.add_bridge_btn.setObjectName("add_bridge_btn")
        self.song_list = QtWidgets.QListWidget(self.centralwidget)
        self.song_list.setGeometry(QtCore.QRect(330, 10, 401, 521))
        self.song_list.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.song_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.song_list.setUniformItemSizes(False)
        self.song_list.setObjectName("song_list")
        self.text_input = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_input.setGeometry(QtCore.QRect(10, 130, 301, 181))
        self.text_input.setObjectName("text_input")
        self.add_song_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_song_btn.setGeometry(QtCore.QRect(80, 480, 141, 41))
        self.add_song_btn.setObjectName("add_song_btn")
        self.remove_item_btn = QtWidgets.QPushButton(self.centralwidget)
        self.remove_item_btn.setGeometry(QtCore.QRect(10, 350, 75, 23))
        self.remove_item_btn.setObjectName("remove_item_btn")
        addSongWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(addSongWindow)
        QtCore.QMetaObject.connectSlotsByName(addSongWindow)

    def retranslateUi(self, addSongWindow):
        _translate = QtCore.QCoreApplication.translate
        addSongWindow.setWindowTitle(_translate("addSongWindow", "New Song"))
        self.song_title.setPlaceholderText(_translate("addSongWindow", "Enter song title"))
        self.add_couplet_btn.setText(_translate("addSongWindow", "add couplet"))
        self.add_chour_btn.setText(_translate("addSongWindow", "add chour"))
        self.add_bridge_btn.setText(_translate("addSongWindow", "add bridge"))
        self.add_song_btn.setText(_translate("addSongWindow", "Add song"))
        self.remove_item_btn.setText(_translate("addSongWindow", "remove item"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addSongWindow = QtWidgets.QMainWindow()
    ui = Ui_addSongWindow()
    ui.setupUi(addSongWindow)
    addSongWindow.show()
    sys.exit(app.exec_())
