# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ss.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(648, 511)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_songs = QtWidgets.QListWidget(self.centralwidget)
        self.list_songs.setGeometry(QtCore.QRect(10, 40, 221, 391))
        self.list_songs.setObjectName("list_songs")
        self.list_words = QtWidgets.QListWidget(self.centralwidget)
        self.list_words.setGeometry(QtCore.QRect(240, 20, 391, 411))
        self.list_words.setUniformItemSizes(False)
        self.list_words.setObjectName("list_words")
        self.search_input = QtWidgets.QLineEdit(self.centralwidget)
        self.search_input.setGeometry(QtCore.QRect(10, 20, 221, 20))
        self.search_input.setObjectName("search_input")
        self.screensCB = QtWidgets.QComboBox(self.centralwidget)
        self.screensCB.setGeometry(QtCore.QRect(10, 460, 181, 22))
        self.screensCB.setObjectName("screensCB")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 440, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.checkbox_stream_mode = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_stream_mode.setGeometry(QtCore.QRect(310, 460, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkbox_stream_mode.setFont(font)
        self.checkbox_stream_mode.setObjectName("checkbox_stream_mode")
        self.checkbox_show_words = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_show_words.setGeometry(QtCore.QRect(210, 460, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkbox_show_words.setFont(font)
        self.checkbox_show_words.setObjectName("checkbox_show_words")
        self.btn_set = QtWidgets.QPushButton(self.centralwidget)
        self.btn_set.setGeometry(QtCore.QRect(420, 460, 101, 23))
        self.btn_set.setObjectName("btn_set")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ScreenShower"))
        self.search_input.setPlaceholderText(_translate("MainWindow", "Пошук..."))
        self.label.setText(_translate("MainWindow", "Availabel screens:"))
        self.checkbox_stream_mode.setText(_translate("MainWindow", "Stream mode"))
        self.checkbox_show_words.setText(_translate("MainWindow", "Show words"))
        self.btn_set.setText(_translate("MainWindow", "set"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
