# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ss.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget
from other_window import Ui_OtherWindow


class Ui_MainWindow(object):
    # def open_window(self):
    #     self.window = QtWidgets.QMainWindow()
    #     self.ui = Ui_OtherWindow()
    #     self.ui.setupUi(self.window)
    #     self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 286)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_print = QtWidgets.QPushButton(self.centralwidget)
        self.btn_print.setGeometry(QtCore.QRect(260, 132, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_print.setFont(font)
        self.btn_print.setObjectName("btn_print")
        # self.btn_print.clicked.connect(self.open_window)
        self.aScreens_cb = QtWidgets.QComboBox(self.centralwidget)
        self.aScreens_cb.setGeometry(QtCore.QRect(90, 140, 151, 22))
        self.aScreens_cb.setObjectName("aScreens_cb")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 110, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_print.setText(_translate("MainWindow", "Print"))
        self.label.setText(_translate("MainWindow", "Avaliable screens:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
