# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditSongWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditSongWindow(object):
    def setupUi(self, EditSongWindow):
        EditSongWindow.setObjectName("EditSongWindow")
        EditSongWindow.resize(740, 542)
        self.centralwidget = QtWidgets.QWidget(EditSongWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.save_item_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_item_btn.setGeometry(QtCore.QRect(230, 320, 75, 23))
        self.save_item_btn.setObjectName("save_item_btn")
        self.edit_song_btn = QtWidgets.QPushButton(self.centralwidget)
        self.edit_song_btn.setGeometry(QtCore.QRect(80, 480, 141, 41))
        self.edit_song_btn.setObjectName("edit_song_btn")
        self.add_bridge_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_bridge_btn.setGeometry(QtCore.QRect(120, 350, 111, 23))
        self.add_bridge_btn.setObjectName("add_bridge_btn")
        self.song_title = QtWidgets.QLineEdit(self.centralwidget)
        self.song_title.setGeometry(QtCore.QRect(10, 10, 310, 20))
        self.song_title.setObjectName("song_title")
        self.add_couplet_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_couplet_btn.setGeometry(QtCore.QRect(10, 320, 111, 23))
        self.add_couplet_btn.setObjectName("add_couplet_btn")
        self.remove_item_btn = QtWidgets.QPushButton(self.centralwidget)
        self.remove_item_btn.setGeometry(QtCore.QRect(10, 350, 111, 23))
        self.remove_item_btn.setObjectName("remove_item_btn")
        self.add_chour_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_chour_btn.setGeometry(QtCore.QRect(120, 320, 111, 23))
        self.add_chour_btn.setObjectName("add_chour_btn")
        self.song_list = QtWidgets.QListWidget(self.centralwidget)
        self.song_list.setGeometry(QtCore.QRect(330, 10, 401, 521))
        self.song_list.setDragEnabled(False)
        self.song_list.setDragDropOverwriteMode(False)
        self.song_list.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.song_list.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.song_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.song_list.setUniformItemSizes(False)
        self.song_list.setObjectName("song_list")
        self.text_input = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_input.setGeometry(QtCore.QRect(10, 130, 311, 181))
        self.text_input.setObjectName("text_input")
        EditSongWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EditSongWindow)
        QtCore.QMetaObject.connectSlotsByName(EditSongWindow)

    def retranslateUi(self, EditSongWindow):
        _translate = QtCore.QCoreApplication.translate
        EditSongWindow.setWindowTitle(_translate("EditSongWindow", "Edit song"))
        self.save_item_btn.setText(_translate("EditSongWindow", "save"))
        self.edit_song_btn.setText(_translate("EditSongWindow", "Edit song"))
        self.add_bridge_btn.setText(_translate("EditSongWindow", "add bridge"))
        self.song_title.setPlaceholderText(_translate("EditSongWindow", "Enter song title"))
        self.add_couplet_btn.setText(_translate("EditSongWindow", "add couplet"))
        self.remove_item_btn.setText(_translate("EditSongWindow", "remove item"))
        self.add_chour_btn.setText(_translate("EditSongWindow", "add chour"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditSongWindow = QtWidgets.QMainWindow()
    ui = Ui_EditSongWindow()
    ui.setupUi(EditSongWindow)
    EditSongWindow.show()
    sys.exit(app.exec_())
