# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_testWindow(object):
    def setupUi(self, testWindow):
        testWindow.setObjectName("testWindow")
        testWindow.resize(345, 564)
        self.centralwidget = QtWidgets.QWidget(testWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 301, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 50, 301, 461))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 520, 301, 41))
        self.pushButton.setObjectName("pushButton")
        testWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(testWindow)
        QtCore.QMetaObject.connectSlotsByName(testWindow)

    def retranslateUi(self, testWindow):
        _translate = QtCore.QCoreApplication.translate
        testWindow.setWindowTitle(_translate("testWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("testWindow", "Enter song title"))
        self.plainTextEdit.setPlaceholderText(_translate("testWindow", "Enter song text"))
        self.pushButton.setText(_translate("testWindow", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    testWindow = QtWidgets.QMainWindow()
    ui = Ui_testWindow()
    ui.setupUi(testWindow)
    testWindow.show()
    sys.exit(app.exec_())
