# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'words_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WordsWindow(object):
    def setupUi(self, WordsWindow):
        WordsWindow.setObjectName("WordsWindow")
        WordsWindow.resize(881, 718)
        WordsWindow.setStyleSheet("color: black;\n"
"background-color: white;")
        self.centralwidget = QtWidgets.QWidget(WordsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 130, 641, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setStyleSheet("text-align: center;")
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        WordsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(WordsWindow)
        QtCore.QMetaObject.connectSlotsByName(WordsWindow)

    def retranslateUi(self, WordsWindow):
        _translate = QtCore.QCoreApplication.translate
        WordsWindow.setWindowTitle(_translate("WordsWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WordsWindow = QtWidgets.QMainWindow()
    ui = Ui_WordsWindow()
    ui.setupUi(WordsWindow)
    WordsWindow.show()
    sys.exit(app.exec_())
